### ISSUE TITLE
Add Support for section background settings 

### ISSUE THREAD

**Issue by joaoferreira** [SharePoint/PnP-Provisioning-Schema#372] opened 2019-01-31 15:34 UTC
With the latest schema version is not possible to create the landing pages with the same background sections that were defined in the template site.
It would be nice to have this as an option on future versions.
Below are two screen shots of original site and the result after applying the template.
![original](https://user-images.githubusercontent.com/3533126/52065004-9ac86c80-256d-11e9-94fd-18b9abf5ba14.JPG)
![template](https://user-images.githubusercontent.com/3533126/52065005-9b610300-256d-11e9-978f-1b5e260508bd.JPG)

**Comment by jansenbe** [comment] 2019-02-06 09:15
Duplicate of #356, will close this one

**Closed by jansenbe** 2019-02-06 09:15 UTC
