### ISSUE TITLE
Apply-SPOProvisioningTemplate : The provided template is not valid!

### ISSUE THREAD

**Issue by ntinykumar** [SharePoint/PnP-Provisioning-Schema#126] opened 2016-09-29 08:35 UTC
I have done this migration from free trail tenant to tenant using  using PnP provision engine approach. This work perfectly fine but when I actually get the template xml file from my client SharePoint online 2013 site and when apply template to another tenant give below error which we could not able to find out.

PS D:\t> Apply-SPOProvisioningTemplate .\PnPDemo.xml
Apply-SPOProvisioningTemplate : The provided template is not valid!
At line:1 char:1
- Apply-SPOProvisioningTemplate .\PnPDemo.xml
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : WriteError: (:) [Apply-SPOProvisioningTemplate], ApplicationException
  - FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate

Your help is appreciated.

**Comment by PaoloPia** [comment] 2016-12-02 12:47
Hi,
Thanks for using the PnP Provisioning Engine. Can you share the template XML?

**Comment by VesaJuvonen** [comment] 2017-01-31 11:13
This issue was moved to SharePoint/PnP-Sites-Core#1027

**Comment by VesaJuvonen** [comment] 2017-01-31 11:13
Hi ntinykumar, 
only way we can validate the issue is to have access on the template, so we would appreciate to have a closer look on used template. Since this issue is also around the actual PnP provisioning engine, will relocate this issue to PnP-Sites-Core and close this one.

**Closed by VesaJuvonen** 2017-01-31 11:13 UTC
