### ISSUE TITLE
"EnableVersioning" on ListInstance causing error "Specified method is not supported" (2018/05)+

### ISSUE THREAD

**Issue by balle3201** [SharePoint/PnP-Provisioning-Schema#339] opened 2018-10-04 08:18 UTC
The attribute 'EnableVersioning='true'' is now causing an error to occur  if combined with 'MaxVersionLimit="0"' while applying a PnP Template (2018/05). This has worked perfectly until recently.

The errormessage states as follows: 

> Specified method is not supported 

As I understand there is a global change currently rolling out to all O365 tenants, which enforces a default of "Major Versions" (max 500 versions), and it seems that this attribute is causing the PnP Provisioning Engine to fail if supplied.

**(MC138148, minimum 500 versions and versioning cannot be disabled)**

A bit of testing reveals that supplying 'EnableVersioning="true"' with a value for MaxVersionLimit **other** than 0 (zero) seems to work however. (> 1 for instance)

The latest PnP Schema 2018/07 also states that this attribute is supported, and I guess it is still relevant for that version as well.

**Comment by pkskelly** [comment] 2018-10-24 17:47
Just to confirm this issue.  Appeared for me as well on previously functional template. 

With attribute 'EnableVersioning='true'', error `Specified method is not supported` is returned in tracing log if combined with 'MaxVersionLimit="0"' while applying a PnP Template (2018/05). 

Template file using schema from 2018/05 and PnP PowerShell 3.2.1810.0.  Changing the MaxVersionLimit to >0 resolves issue.

**Comment by armchairdeity** [comment] 2018-11-01 19:39
Confirmed. Not sure what the repercussions of setting that value to 1 is, but I'll give it a try.

I can confirm that this is still an issue... tho I haven't updated recently.

My provisioning templates are generated by someone else, and I'm not technically supposed to edit them, but I am going to and try to provision again and we will see what happens. I'll let you know.

**Comment by Suuzshine** [comment] 2018-11-02 11:04
Hi, I just looked at this issue and the issue seems to be fixed. I rolled out a template with  'EnableVersioning='true'' and 'MaxVersionLimit="0" and the site is created without any errors. Anybody else seeing it work again?

**Comment by PaoloPia** [comment] 2019-03-12 17:45
Hi,
Thanks for your feedback. Based on the latest messages it looks solved and I will close this item.

**Closed by PaoloPia** 2019-03-12 17:45 UTC
