### ISSUE TITLE
DataRows does not work with some Lists

### ISSUE THREAD

**Issue by AndreyFedotov** [SharePoint/PnP-Provisioning-Schema#140] opened 2016-11-09 13:21 UTC
I'm creating a List and get Title from resource file:
`<pnp:ListInstance Title="{resource:list_PurchaseTypes}" Description="PnP Demo List" TemplateType="100" Url="Lists/PurchaseTypes"...`

I am also try to add initial data:
`<pnp:DataRows>
            <pnp:DataRow>
              <pnp:DataValue FieldName="Title">blablabla</pnp:DataValue>
            </pnp:DataRow>
          </pnp:DataRows>`

But I'v got an exception during Apply-PnPProvisioningTemplate:

Apply-PnPProvisioningTemplate : List '{resource:list_PurchaseTypes}' does not exist at site with URL 'https://..../sites/...'.
At C:\Development\temp\PnP.DemoProvisioning\CoonectAndApply.ps1:7 char:1
Apply-PnPProvisioningTemplate -Path "C:\Development\temp\PnP.DemoProvisioning\mo ...
    CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

If I change list Title to  Title="Purchase Types" code completes successfully

**Comment by PaoloPia** [comment] 2016-12-02 16:29
Hi,
Thanks for your feedback. This issue have been fixed in late October (https://github.com/SharePoint/PnP-Sites-Core/commit/bf5fe327ac616a83488ae26a4b7e252fec282ca3). Thus, I will close this item. Feel free to re-open it if you think that the issue is not yet completely fixed. Thanks.

**Closed by PaoloPia** 2016-12-02 16:29 UTC
