### ISSUE TITLE
pnp:Navigation seems not to be applied on Modern Team Site

### ISSUE THREAD

**Issue by patrick-blanc** [SharePoint/PnP-Provisioning-Schema#260] opened 2017-10-23 13:08 UTC
Navigation in PnP templates are not applied to modern team site. 

`<pnp:Navigation>`

Cheers
Patrick

**Comment by BraunJonathan** [comment] 2018-01-12 09:32
I tried to setup a navigation in Pnp on a modern comm Site and it doesn't seem to work either.

Is this a known issue?

**Comment by prawnz** [comment] 2018-05-01 11:14
This is likely caused by the Publishing Feature not available in Modern Sites.  I encountered the same situation as well

**Comment by PaoloPia** [comment] 2019-03-12 16:33
Hi,
Thanks for your feedback. Navigation is nowadays supported at the engine level. Thus, I will close this item.

**Closed by PaoloPia** 2019-03-12 16:33 UTC
